// pub mod token;

use std::fmt;
use super::chartype::CharType;

/// Represents a token generated by the lexer during the parsing stage; generally groups
/// several contiguous characters by their type as defined in the CharType enum
#[derive(PartialEq, Debug, Clone)]
pub struct Token {
    pub content: String,
    pub chartype: CharType
}

/// Allows printing of Tokens and conversion from Tokens to Strings
impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.content)
    }
}

impl Token {
    /// Convenience constructor for Token instances
    pub fn new(value: &str, t: CharType) -> Token {
        return Token {
            content: String::from(value),
            chartype: t
        };
    }
}
