# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://generic-github-user.github.io/random-walks/"

git_url = "https://github.com/generic-github-user/random-walks/tree/main/"

def custom_doc_links(name): return None
