# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Geometry": "00_fold.ipynb",
         "Point": "00_fold.ipynb",
         "Line": "00_fold.ipynb",
         "Polygon": "00_fold.ipynb",
         "Circle": "00_fold.ipynb",
         "Manifold": "00_fold.ipynb",
         "Foldable": "00_fold.ipynb",
         "F": "00_fold.ipynb"}

modules = ["fold.py"]

doc_url = "https://generic-github-user.github.io/FoldZ/"

git_url = "https://github.com/generic-github-user/FoldZ/tree/main/"

def custom_doc_links(name): return None
