# AUTOGENERATED! DO NOT EDIT! File to edit: 00_fold.ipynb (unless otherwise specified).

__all__ = ['Geometry', 'Point', 'Line', 'Polygon', 'Circle', 'Manifold', 'Foldable', 'F']

# Cell
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np
import svgwrite
import random

import sympy
from sympy import Point2D, Point3D, Segment, Polygon, N, Rational, pi
from sympy.abc import x, y, z, t

import math

from IPython.display import display, SVG
